### ISSUE TITLE
Support for VS 2015

### ISSUE THREAD

**Issue by vladascibulskis** [Igorbek/CodeContracts.MSBuild#2]
Current package doesn't work with VS 2015 build, because of the error:
..\packages\CodeContracts.MSBuild.1.7.11202.1001\build\CodeContracts.MSBuild.targets(6,5): error MSB4019: The imported project "..\packages\CodeContracts.MSBuild.1.7.11202.1001\Contracts\MsBuild\v14.0\Microsoft.CodeContracts.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. [..\Sources\WNP.Listener\Core\Core.csproj]

The problem is that there is no v14.0 directory in the package. Please update the nugget package with latest MsBuild version.

**Comment by Igorbek** [comment]
Thanks for reporting. PR #3 addresses this issue.

**Comment by Igorbek** [comment]
[v1.9.10714.2001](https://github.com/Igorbek/CodeContracts.MSBuild/releases/tag/v1.9.10714.2001) has been released.
