### ISSUE TITLE
Contracts version out of date

### ISSUE THREAD

**Issue by Z00L** [Igorbek/CodeContracts.MSBuild#4]
Hey Igor,
maybe you could update your nuget package to the latest code contracts version?

**Comment by Igorbek** [comment]
[CodeContracts 1.9.10714.2](https://github.com/Microsoft/CodeContracts/releases/tag/v1.9.10714.2) is [the latest release](https://github.com/Microsoft/CodeContracts/releases/latest). This is what in my nuget package.
Do you want me to update to [RC 1.10.20606.1](https://github.com/Microsoft/CodeContracts/releases/tag/v1.10.20606.1)?

**Comment by Z00L** [comment]
No, you are right, my mistake. However, a recent prerelease would be nice as there are some fixes since last stable release.

**Comment by kkm000** [comment]
Yes, please update the binaries to 1.10RC! These are the latest working with Roslyn compiled C# 6. There were multiple fixes done by the project members, and I am hitting the issue (https://github.com/Microsoft/CodeContracts/issues/169) that has been fixed more than 2 years ago (https://github.com/Microsoft/CodeContracts/pull/276).

Release 1.10 is unlikely, unfortunately. The tools break with C# 7 so badly that there no fix, barring a complete rewrite.  Something like https://github.com/AArnott/CodeGeneration.Roslyn may be the future replacement.

**Comment by Igorbek** [comment]
I will create a prerelease version with updated binaries. Give me a couple days.

**Comment by yaakov-h** [comment]
Don't bother tagging me, I can't do anything about it.

**Comment by Igorbek** [comment]
[Version 1.11-alpha](https://github.com/Igorbek/CodeContracts.MSBuild/releases/tag/1.11.0-alpha) has been released.
It will be promoted to 1.11 after 2 weeks if it works well.

**Comment by kkm000** [comment]
Fantastic, thank you! I'll give it a try tomorrow AM.

On 2 Dec 2017 5:24 p.m., Igor Oleinikov <notifications@github.com> wrote:

Version 1.11-alpha<https://github.com/Igorbek/CodeContracts.MSBuild/releases/tag/1.11.0-alpha> has been released.
It will be promoted to 1.11 after 2 weeks if it works well.

**Comment by kkm000** [comment]
Thank you, the tools worked on a few projects I tested!

There's a minor issue, the built contract assemblies are not registered as project outputs, and aren't therefore packaged by the Pack target. This is expected, since the original scripts pre-date MSBuild NuGet integration. I'll send you a small PR with the fix.

**Comment by kkm000** [comment]
Hi Igor, so it seems fixing the packaging issue is blocked on NuGet. I do not have much time to work on that now, have a lot of debt to other OSS projects besides my job. Do you think it's time to release what we have now as 11.1 no alpha? Accepting the refactoring request #13 is up to you. It is only a refactoring, in preparation for the future NuGet fix, no functional changes there, just tidying up stuff.

The addition of default .props is not in the published 11.1-alpha. We would certainly benefit from it, thanks!

**Comment by Igorbek** [comment]
Hey @kkm000, sorry for the delay. I was also super busy with other stuff.
That is definitely the time to publish release with the latest changes. I will not take #13 for now, as it requires more careful review. But it would be a great starting point for later updates.
I will publish a new release shortly. I'm thinking of making existing `1.11-alpha` an official `1.11`. And I will publish `1.12-rc` with your recent great changes.
Thank you for pushing me, it is really appreciated!

**Comment by Igorbek** [comment]
`1.11` and `1.12-rc` have been published. I'll give a couple weeks for RC.
